### ISSUE TITLE
Graphql method in the new version

### ISSUE THREAD

**Issue by Charly9978** [nuxt-community/strapi-module#199]
Hello,

First, thanks you for this very useful module.

I saw that the graphql method disappear in the new version of the plugin.

For my personal knowledge, i have two questions:
- why?
- what is the best way to replace this method ( i don't really want install appolo client...)?

thanks you for your help

**Comment by kadlinobit** [comment]
Hi, 
I'd like to ask a follow-up question - is **nuxt-community/strapi-module** using [Strapi SDK](https://strapi-sdk-js.netlify.app/) under the hood?

They've dropped graphQL API recently as well, so that leads me to this question. I'm just curious - not that I have any opinion whether it's good or bad.

**Comment by benjamincanac** [comment]
Closing this as mentioned in https://github.com/nuxt-community/strapi-module/issues/207#issuecomment-1009987423, a new [useStrapiGraphQL](https://strapi.nuxtjs.org/usage#usestrapigraphql) composable has been added in [v1.1.0](https://github.com/nuxt-community/strapi-module/releases/tag/v1.1.0).

**Comment by benjamincanac** [comment]
@kadlinobit As mentioned in https://github.com/nuxt-community/strapi-module/issues/163#issuecomment-1008974844, the strapi module is unfortunately unable to use the Strapi SDK.
