### ISSUE TITLE
User object is huge and slow to load if the user is prolific

### ISSUE THREAD

**Issue by adamkhan** [nuxt-community/strapi-module#69]
Logging in is taking a long time, and I realize it's because the user object has contained within it all the content entries that user has made. I don't need them here.

Where is this set? Perhaps a toggle somewhere to exclude (or include) the user's authored content? Or perhaps this is something that can be set within Strapi. Heading over there to check...

**Comment by adamkhan** [comment]
The problem has come up before. For now the Strapi guys have posted a solution at https://github.com/strapi/strapi/discussions/4913.

**Comment by benjamincanac** [comment]
@adamkhan This issue is not related to `@nuxtjs/strapi`, this module wraps the API calls to Strapi like https://github.com/strapi/strapi-sdk-javascript but for [NuxtJS](https://nuxtjs.org/).

To configure what Strapi sends you back and make your user object lighter when calling `/users/me`, you can:

- edit `extensions/users-permissions/models/User.settings.json` and configure the relations to `autoPopulate: false`
- override `extensions/users-permissions/services/User.js` `fetchAuthenticatedUser` method to only populate what you want
- override `extensions/users-permissions/controllers/User.js` `me` method to return only what you need
