### ISSUE TITLE
Per Session Authentication no longer possible

### ISSUE THREAD

**Issue by blefevre** [nuxt-community/strapi-module#92]
### Version
@nuxtjs/strapi: v0.1.9
nuxt: v2.14.12

#87 has introduced a change that stores the JWT token in both a cookie and localstorage.
This has made it impossible to have a user's authentication expire at the end of the browser session, because it gets read back from localstorage even if the cookie has expired or been cleared.

Previously I was setting the cookie like this, allowing me to have a configurable remember me option:
```javascript
const cookieParams: any = {
  secure: true,
}
if (this.rememberMe) {
  cookieParams.maxAge = 31536000 // 1 Year
}

// Manually set token so we can adjust params
this.$strapi.$http.setToken(response.jwt, 'Bearer')
this.$strapi.$cookies.set('strapi_jwt', response.jwt, cookieParams)
```

Localstorage should be opt-in, and better access to cookie params in `this.$strapi.setToken` per #85 and #70 would be good too.

**Comment by pi0** [comment]
I think it would be better to wait for a stable universal expiration with `@nuxt/session` (since i think currently module is not having a built-in way to support expiration) and meanwhile having an option to disable LS integration (opt-out) since is enforced in sync method. (Can be implemented with a global flag like `const localStorageEnabled = typeof localstorage !== undefined && <?= options.localstorage ?>`
